=== Helioviewer-Project/api/docroot/schema/client_state.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://api.helioviewer.org/schema/client_state.schema.json",
    "title": "Client State",
    "description": "State information used to initialize the helioviewer.org UI",
    "additionalProperties": false,
    "type": "object",
    "properties": {
        "date": { "type": "number" },
        "centerX": { "type": "number" },
        "centerY": { "type": "number" },
        "imageScale": { "type": "number" },
        "eventLayers": {
            "type": "object",
            "patternProperties": {
                "^[a-zA-Z_]{1,11}$": {
                    "$ref": "https://api.helioviewer.org/schema/event_group.schema.json"
                }
            },
            "additionalProperties": false
        },
        "imageLayers": {
            "type": "array",
            "items": {
                "$ref": "https://api.helioviewer.org/schema/image_layer.schema.json"
            }
        },
        "celestialBodies": {
            "$ref": "https://api.helioviewer.org/schema/celestial_bodies.schema.json"
        }
    },
    "required": [
        "date",
        "centerX",
        "centerY",
        "imageScale",
        "eventLayers",
        "imageLayers",
        "celestialBodies"
    ]
}

=== Helioviewer-Project/api/tests/unit_tests/validation/test_data/client_state/valid/valid_17.json
{
  "date": 1410269529000,
  "imageScale": 4.84088176,
  "centerX": -2894.0322215830834,
  "centerY": 101.72638697583727,
  "imageLayers": [
    {
      "end": "2024-07-29 17:33:45",
      "start": "2010-06-02 00:05:36",
      "opacity": 100,
      "visible": true,
      "diffTime": 1,
      "nickname": "AIA 171",
      "sourceId": 10,
      "uiLabels": [
        {
          "label": "Observatory",
          "name": "SDO"
        },
        {
          "label": "Instrument",
          "name": "AIA"
        },
        {
          "label": "Measurement",
          "name": "171"
        }
      ],
      "diffCount": 60,
      "Instrument": "AIA",
      "difference": 0,
      "Measurement": "171",
      "Observatory": "SDO",
      "baseDiffTime": "2024-07-19T13:28:50.000Z",
      "layeringOrder": 1
    }
  ],
  "eventLayers": {
    "tree_HEK": {
      "id": "HEK",
      "layers": [
        {
          "event_type": "AR",
          "frms": [
            "HMI_SHARP",
            "NOAA_SWPC_Observer",
            "SPoCA"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CC",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CD",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CH",
          "frms": [
            "SPoCA"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CJ",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CE",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CR",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "CW",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "EF",
          "frms": [
            "Emerging_flux_region_module"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "ER",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "FI",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "FA",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "FE",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "FL",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "LP",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "OS",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "PG",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "SG",
          "frms": [
            "Sigmoid_Sniffer"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "SP",
          "frms": [
            "all"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "SS",
          "frms": [
            "EGSO_SFC"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "TO",
          "frms": [
            "SSW_PFSS_v2_\\+_null_point_finder_v20180808"
          ],
          "event_instances": [],
          "open": 1
        }
      ],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    },
    "tree_CCMC": {
      "id": "CCMC",
      "layers": [
        {
          "event_type": "C3",
          "frms": [
            "CME"
          ],
          "event_instances": [],
          "open": 1
        },
        {
          "event_type": "FP",
          "frms": [
            "MAG4_LoS_FEr"
          ],
          "event_instances": [],
          "open": 1
        }
      ],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    },
    "tree_RHESSI": {
      "id": "RHESSI",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    }
  },
  "celestialBodies": {
    "soho": [],
    "stereo_a": [
      "stereo_a-mercury-tree-label"
    ],
    "stereo_b": []
  }
}

=== Helioviewer-Project/api/tests/unit_tests/validation/test_data/valid/valid_3.json
{
  "date": 1718087894000,
  "centerX": -2401.07735296,
  "centerY": -1316.71983872,
  "imageScale": 77.45410816,
  "eventLayers": {
    "tree_HEK": {
      "id": "HEK",
      "layers": [
        {
          "frms": [
            "NOAA_SWPC_Observer"
          ],
          "open": 1,
          "event_type": "AR",
          "event_instances": []
        },
        {
          "frms": [
            "EGSO_SFC"
          ],
          "open": 1,
          "event_type": "SS",
          "event_instances": []
        }
      ],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": false
    },
    "tree_CCMC": {
      "id": "CCMC",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    },
    "tree_RHESSI": {
      "id": "RHESSI",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    }
  },
  "imageLayers": [
    {
      "end": "2024-04-08 06:30:13",
      "start": "2024-04-08 06:19:24",
      "opacity": 35,
      "visible": true,
      "diffTime": 1,
      "nickname": "IRIS SJI 2796",
      "sourceId": 89,
      "uiLabels": [
        {
          "name": "IRIS",
          "label": "Observatory"
        },
        {
          "name": "SJI",
          "label": "Instrument"
        },
        {
          "name": "2796",
          "label": "Measurement"
        }
      ],
      "diffCount": 60,
      "Instrument": "SJI",
      "difference": 0,
      "Measurement": "2796",
      "Observatory": "IRIS",
      "baseDiffTime": "2024/06/12 08:32:57",
      "layeringOrder": 1
    },
    {
      "end": "2024-06-11 06:38:14",
      "start": "2012-07-05 00:09:05",
      "opacity": 100,
      "visible": "1",
      "diffTime": 1,
      "nickname": "AIA 1600",
      "sourceId": 15,
      "uiLabels": [
        {
          "name": "SDO",
          "label": "Observatory"
        },
        {
          "name": "AIA",
          "label": "Instrument"
        },
        {
          "name": "1600",
          "label": "Measurement"
        }
      ],
      "diffCount": 60,
      "Instrument": "AIA",
      "difference": 0,
      "Measurement": "1600",
      "Observatory": "SDO",
      "baseDiffTime": "2024/04/08 05:30:13",
      "layeringOrder": 1
    }
  ],
  "celestialBodies": {
    "soho": [
      "soho-mercury-tree-label",
      "soho-mars-tree-label",
      "soho-jupiter-tree-label",
      "soho-saturn-tree-label",
      "soho-uranus-tree-label",
      "soho-neptune-tree-label"
    ],
    "stereo_a": [
      "stereo_a-mercury-tree-label",
      "stereo_a-earth-tree-label",
      "stereo_a-mars-tree-label",
      "stereo_a-jupiter-tree-label",
      "stereo_a-saturn-tree-label",
      "stereo_a-uranus-tree-label",
      "stereo_a-psp-tree-branch"
    ],
    "stereo_b": [
      "stereo_b-mercury-tree-label"
    ]
  }
}

=== Helioviewer-Project/api/tests/unit_tests/validation/test_data/valid/valid_7.json
{
  "date": 1715731311000,
  "centerX": 1471.6280550400002,
  "centerY": 2168.71502848,
  "imageScale": 77.45410816,
  "eventLayers": {
    "tree_HEK": {
      "id": "HEK",
      "layers": [
        {
          "frms": [
            "NOAA_SWPC_Observer"
          ],
          "open": 1,
          "event_type": "AR",
          "event_instances": []
        },
        {
          "frms": [
            "EGSO_SFC"
          ],
          "open": 1,
          "event_type": "SS",
          "event_instances": []
        }
      ],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": false
    },
    "tree_CCMC": {
      "id": "CCMC",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    },
    "tree_RHESSI": {
      "id": "RHESSI",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    }
  },
  "imageLayers": [
    {
      "opacity": 100,
      "visible": true,
      "diffTime": 1,
      "uiLabels": [
        {
          "name": "SDO",
          "label": "Observatory"
        },
        {
          "name": "AIA",
          "label": "Instrument"
        },
        {
          "name": "1600",
          "label": "Measurement"
        }
      ],
      "diffCount": 60,
      "Instrument": "AIA",
      "difference": 0,
      "Measurement": "1600",
      "Observatory": "SDO",
      "baseDiffTime": "2024-06-17T10:49:02.000Z"
    }
  ],
  "celestialBodies": {
    "soho": [
      "soho-mercury-tree-label",
      "soho-mars-tree-label",
      "soho-jupiter-tree-label",
      "soho-uranus-tree-label"
    ],
    "stereo_a": [
      "stereo_a-mercury-tree-label",
      "stereo_a-venus-tree-label",
      "stereo_a-earth-tree-label",
      "stereo_a-mars-tree-label",
      "stereo_a-jupiter-tree-label",
      "stereo_a-saturn-tree-label",
      "stereo_a-uranus-tree-label",
      "stereo_a-neptune-tree-label",
      "stereo_a-psp-tree-branch"
    ],
    "stereo_b": [
      "stereo_b-mercury-tree-label",
      "stereo_b-earth-tree-label",
      "stereo_b-mars-tree-label",
      "stereo_b-jupiter-tree-label",
      "stereo_b-saturn-tree-label"
    ]
  }
}
