=== Helioviewer-Project/api/docroot/schema/post_screenshot.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://api.helioviewer.org/schema/post_screenshot.schema.json",
    "title": "Post Screenshot Parameters",
    "description": "Information used to generate a screenshot via helioviewer.org",
    "type": "object",
    "required": ["date", "imageScale", "layers"],
    "additionalProperties": false,
    "properties": {
        "date": {
            "type": "string",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z$"
        },
        "imageScale": { "type": "number" },
        "layers": {
            "type": "string",
            "maxLength": 1000,
            "pattern": "^[\\_\\w\\]\\[,\\-:\\.\\+ ]+$"
        },
        "eventsState": {
            "$ref": "https://api.helioviewer.org/schema/event_layers.schema.json"
        },
        "scale": { "type": "boolean" },
        "scaleType": {
            "type": "string",
            "enum": [
                "earth", "scalebar", "disabled"
            ]
        },
        "scaleX": { "type": "number" },
        "scaleY": { "type": "number" },
        "width": { "type": "number" },
        "height": { "type": "number" },
        "x0": { "type": "number" },
        "y0": { "type": "number" },
        "x1": { "type": "number" },
        "y1": { "type": "number" },
        "x2": { "type": "number" },
        "y2": { "type": "number" },
        "display": { "type": "boolean" },
        "watermark": { "type": "boolean" },
        "switchSources": { "type": "boolean" },
        "movieIcons": { "type": "boolean" },
        "celestialBodiesLabels": {
            "type": "string",
            "maxLength": 1000,
            "pattern": "^[a-zA-Z_\\-,]*$"
        },
        "celestialBodiesTrajectories": {
            "type": "string",
            "maxLength": 1000,
            "pattern": "^[a-zA-Z_\\-,]*$"
        },
        "callback": {
            "type": "string",
            "maxLength": 1000
        }
    }
}

=== Helioviewer-Project/api/tests/unit_tests/validation/test_data/post_screenshot/valid/post_screenshot_1.json
{
  "imageScale": 5.608481803348903,
  "layers": "[SDO,AIA,131,1,100,0,60,1,2018-03-30T04:18:36.000Z]",
  "eventsState": {
    "tree_HEK": {
      "id": "HEK",
      "layers": [
        {
          "event_type": "CE",
          "frms": [
            "CACTus_\\(Computer_Aided_CME_Tracking\\)"
          ],
          "event_instances": [],
          "open": 1
        }
      ],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": false
    },
    "tree_CCMC": {
      "id": "CCMC",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    },
    "tree_RHESSI": {
      "id": "RHESSI",
      "layers": [],
      "visible": true,
      "labels_visible": true,
      "markers_visible": true,
      "layer_available_visible": true
    }
  },
  "scale": true,
  "scaleType": "earth",
  "scaleX": -2334,
  "scaleY": 2122,
  "movieIcons": false,
  "date": "2023-10-22T12:53:07.000Z",
  "display": false,
  "switchSources": false,
  "celestialBodiesLabels": "soho-mercury,soho-venus,soho-mars,soho-jupiter,soho-saturn,soho-uranus,soho-neptune,stereo_b-mercury,stereo_b-venus,stereo_b-earth,stereo_b-mars,stereo_b-jupiter,stereo_b-saturn,stereo_b-uranus,stereo_b-neptune",
  "celestialBodiesTrajectories": "",
  "x1": -3488.4756816830177,
  "x2": 3690.3810266035784,
  "y1": -2585.5101113438445,
  "y2": 4716.733196616427
}
